export default {
    homePage: '.nav.navbar-nav li:nth-child(1)',
    loginPage: '.nav.navbar-nav li:nth-child(4)',
    userName: 'input[data-qa="login-email"]',
    password: 'input[data-qa="login-password"]',
    submit: 'button[data-qa="login-button"]',
    accountName: '.nav.navbar-nav li:nth-child(10) a',
    errorMessage: 'p[style]',
    productsPage: '.nav.navbar-nav li:nth-child(2) a',
    searchBar: '#advertisement #search_product',
    searchButton: '#advertisement #submit_search',
    viewDetails: '.nav.nav-pills.nav-justified',
    addToCart: '.btn.btn-default.cart',
    cartPage: '.nav.navbar-nav li:nth-child(3) a',
    firstCartMessage: '.modal-title.w-100',
    secondCartMessage: '.text-center:nth-child(1)',
    viewCart: '.text-center a',
    cartDescription: '.cart_description a',
    cartPrice: '.cart_price p',
    cartQuantity: '.cart_quantity button',
    cartTotalPrice: '.cart_total_price',
    clearCart: '.cart_quantity_delete',
    cartEmpty: '.text-center b',
    productQuantity: '#quantity',
    checkoutMessage: '.modal-body .text-center',
    checkoutLoginProceed: '.modal-body .text-center a',
    cartCheckout: '.btn.btn-default.check_out',
    cartCheckoutTotalPrice: 'tr td:nth-child(4) p',
    contactUsPage: '.nav.navbar-nav li:nth-child(9) a',
    contactUsName: 'input[data-qa="name"]',
    contactUsEmail: 'input[data-qa="email"]',
    contactUsSubject: 'input[data-qa="subject"]',
    contactUsMessage: 'textarea[data-qa="message"]',
    contactUsSuccessMessage: '.status.alert.alert-success',
    contactUsSubmit: 'input[data-qa="submit-button"]',
    newUserName: 'input[data-qa="signup-name"]',
    newEmail: 'input[data-qa="signup-email"]',
    newUserErrorMessage: 'p[style="color: red;"]',
    newUserSubmit: 'button[data-qa="signup-button"]',
    newUserPassword: 'input[data-qa="password"]',
    newUserFirstName: 'input[data-qa="first_name"]',
    newUserLastName: 'input[data-qa="last_name"]',
    newUserAddress: 'input[data-qa="address"]',
    newUserState: 'input[data-qa="state"]',
    newUserCity: 'input[data-qa="city"]',
    newUserZipcode: 'input[data-qa="zipcode"]',
    newUserMobile: 'input[data-qa="mobile_number"]',
    newUserCountry: 'select[data-qa="country"]',
    newUserCreate: 'button[data-qa="create-account"]',
    newUserMessage: 'h2[data-qa="account-created"]',
    newUserContinue: 'a[data-qa="continue-button"]',
    deleteAccount: '.nav.navbar-nav li:nth-child(5) a',
    deletedUserMessage: 'h2[data-qa="account-deleted"]',
    reviewSection: '.active a',
    reviewName: '#name',
    reviewEmail: '#email',
    reviewContent: 'form #review',
    reviewSubmit: '#button-review',
    reviewMessage: '.alert-success.alert span',
    reviewMessageHidden: '.form-row.hide .alert-success.alert span',
    placeOrderButton: '.btn.btn-default.check_out',
    placeOrderCardName: 'input[data-qa="name-on-card"]',
    placeOrderCardNumber: 'input[data-qa="card-number"]',
    placeOrderCVC: 'input[data-qa="cvc"]',
    placeOrderExpiryMonth: 'input[data-qa="expiry-month"]',
    placeOrderExpiryYear: 'input[data-qa="expiry-year"]',
    placeOrderPayButton: 'button[data-qa="pay-button"]',
    firstOrderMessage: 'h2[data-qa="order-placed"] b',
    secondOrderMessage: 'p[style^="font"]',
    downloadInvoiceButton: '.btn.btn-default.check_out',
    recommendedItems: '.recommended_items',
    recommededAddToCart: '.recommended_items .productinfo .add-to-cart',
    recommendedItemName: '.recommended_items .productinfo p',
    continueShopping: '.btn.btn-success.close-modal.btn-block',
    subscriptionButton: '#subscribe',
    subscriptionEmail: '#susbscribe_email',
    subscriptionMessage: 'div[class$="group"] .alert-success.alert'
};